# =============================================================================
# Buildroot Containerfile — auto-generated by buildroot-reconstructor
# Source: https://github.com/eclipse-ee4j/jaxb-ri.git
# Tag: v2.1.7
# Generated: 2026-07-04T00:41:10Z
# =============================================================================

# JDK version: 5 (source: defaulted, confidence: DEFAULTED)
# Distribution: openjdk (source: defaulted, confidence: DEFAULTED)
FROM docker.io/eclipse-temurin:5-jdk

# Build tool: ant
RUN apt-get update && \
    apt-get install -y --no-install-recommends ant && \
    rm -rf /var/lib/apt/lists/*

ENV SOURCE_DATE_EPOCH=0


RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 --branch 'v2.1.7' 'https://github.com/eclipse-ee4j/jaxb-ri.git' /build
WORKDIR /build


# Reproducible build: pin timestamps
ENV SOURCE_DATE_EPOCH=946684800

# Build command: ant jar (source: observed, confidence: OBSERVED)
RUN ant jar

# Normalize non-reproducible JAR metadata for comparison
RUN for jar in $(find . -name '*.jar' \( -path '*/target/*' -o -path '*/build/libs/*' -o -path '*/build/*' -o -path '*/dist/*' \) 2>/dev/null); do \
      abs=$(readlink -f "$jar") && \
      tmp=$(mktemp -d) && cd "$tmp" && \
      jar xf "$abs" META-INF/ 2>/dev/null && \
      if [ -f META-INF/MANIFEST.MF ]; then \
        sed -i '/^Built-By:/d;/^Build-Jdk:/d;/^Created-By:/d;/^Bnd-LastModified:/d' META-INF/MANIFEST.MF; \
      fi && \
      find META-INF/maven -name pom.properties -exec sed -i '/^#/d' {} \; 2>/dev/null; \
      jar uf "$abs" META-INF/ 2>/dev/null; \
      cd / && rm -rf "$tmp"; \
    done 2>/dev/null || true