# =============================================================================
# Buildroot Containerfile — auto-generated by buildroot-reconstructor
# Source: https://github.com/protocolbuffers/protobuf
# Tag: v3.25.2
# Generated: 2026-06-25T23:24:35Z
# =============================================================================

# Base image from CI container reference (source: CI container reference, confidence: OBSERVED)
FROM eclipse-temurin:11-jdk


ENV SOURCE_DATE_EPOCH=0
ENV USE_BAZEL_VERSION=6.4.0


RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 --branch 'v3.25.2' 'https://github.com/protocolbuffers/protobuf' /build
WORKDIR /build

RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ make python3 curl unzip zip git ca-certificates && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 -o /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel

# Reproducible build: pin timestamps
ENV SOURCE_DATE_EPOCH=946684800

# Build command: cd /build && bazel build //java/core:core_mvn-project --action_env=SOURCE_DATE_EPOCH=0 2>&1 (source: observed, confidence: OBSERVED)
RUN cd /build && bazel build //java/core:core_mvn-project --action_env=SOURCE_DATE_EPOCH=0 2>&1
RUN mkdir -p /build/target && find /build/bazel-bin/java/core/ -name '*core_mvn*project*.jar' -exec cp {} /build/target/protobuf-java-3.25.2.jar \; || cp /build/bazel-bin/java/core/core_mvn-project.jar /build/target/protobuf-java-3.25.2.jar

# Normalize non-reproducible JAR metadata for comparison
RUN for jar in $(find . -name '*.jar' -path '*/target/*' 2>/dev/null); do \
      abs=$(readlink -f "$jar") && \
      tmp=$(mktemp -d) && cd "$tmp" && \
      jar xf "$abs" META-INF/ 2>/dev/null && \
      if [ -f META-INF/MANIFEST.MF ]; then \
        sed -i '/^Built-By:/d;/^Build-Jdk:/d;/^Created-By:/d;/^Bnd-LastModified:/d' META-INF/MANIFEST.MF; \
      fi && \
      find META-INF/maven -name pom.properties -exec sed -i '/^#/d' {} \; 2>/dev/null; \
      jar uf "$abs" META-INF/ 2>/dev/null; \
      cd / && rm -rf "$tmp"; \
    done 2>/dev/null || true
